name: Docker Image CI - UE

on:
  schedule:
    - cron: '00 04 * * Sun'
  push:
    paths:
      - 'ue/**'
    branches: [ master ]
  workflow_dispatch:

jobs:
   docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO_UE }}
          tags: |
            type=raw,enable=true,priority=100,prefix=bullseye-,suffix=-slim,value={{date 'YYYY-MM-DD'}}-{{sha}}
          flavor: |
            latest=true
            prefix=
            suffix=
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:ue"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: BUILD_DATE=${{ steps.date.outputs.date }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
